version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/swagger/swagger.yaml

volumes:
  mongo_data:
