openapi: 3.0.0
info:
  title: TM470 API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: API is healthy

  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - puppyName
                - username
                - password
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                puppyName:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  userId:
                    type: string
        '400':
          description: Missing fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '409':
          description: Username already taken
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '400':
          description: Missing fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /modules:
    get:
      summary: Get all modules with completion status for logged-in user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of training modules
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    title:
                      type: string
                    category:
                      type: string
                    difficulty:
                      type: string
                    imagePath:
                      type: string
                    completed:
                      type: boolean
        '401':
          description: Unauthorized – missing or invalid token
        '500':
          description: Server error
  /module/{id}:
    get:
      summary: Get training module by ID
      parameters:
        - name: id
          in: path
          description: Training module ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Training module details
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  title:
                    type: string
                  category:
                    type: string
                  difficulty:
                    type: string
                  imagePath:
                    type: string
                  trainingSteps:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Module not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /progress/{moduleId}:
    post:
      summary: Mark a module as completed for the logged-in user
      security:
        - bearerAuth: []
      parameters:
        - name: moduleId
          in: path
          description: ID of the module to mark as complete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Module marked as completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  completedModules:
                    type: array
                    items:
                      type: string
        '401':
          description: Unauthorized – user not logged in or invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
